//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S031.MetaStack.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S031.MetaStack.Core.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultConnection.
        /// </summary>
        internal static string DefaultConnection {
            get {
                return ResourceManager.GetString("DefaultConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required interface parameter &apos;{0}. {1}&apos;, not found in the parameter list of operation &apos;{2}&apos;.
        /// </summary>
        internal static string S031_MetaStack_Core_Actions_CreateEvaluator_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Actions.CreateEvaluator.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of operation parameters &apos;{0}&apos;, does not match interface &apos;{1}&apos;.
        /// </summary>
        internal static string S031_MetaStack_Core_Actions_CreateEvaluator_2 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Actions.CreateEvaluator.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The config.json configuration file was not found.
        /// </summary>
        internal static string S031_MetaStack_Core_App_AppHost_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.App.AppHost.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} type does not have a static &quot;Instance&quot; field that returns an instance of DbProviderFactory.
        /// </summary>
        internal static string S031_MetaStack_Core_Data_DbProviderFactories_GetFactory_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Data.DbProviderFactories.GetFactory.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type derived from DbProviderFactory was not found in {0}.
        /// </summary>
        internal static string S031_MetaStack_Core_Data_DbProviderFactories_GetFactory_2 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Data.DbProviderFactories.GetFactory.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An assembly containing definitions for {0} was not found.
        /// </summary>
        internal static string S031_MetaStack_Core_Data_DbProviderFactories_GetFactory_3 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Data.DbProviderFactories.GetFactory.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No library containing definitions for {0}.
        /// </summary>
        internal static string S031_MetaStack_Core_Data_DbProviderFactories_GetFactory_4 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Data.DbProviderFactories.GetFactory.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter a must implements IEnumerable&lt;&gt; interface.
        /// </summary>
        internal static string S031_MetaStack_Core_Data_MdbContext_array2List_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Data.MdbContext.array2List.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IEnumerable &lt;{0}&gt; argument type not supported.
        /// </summary>
        internal static string S031_MetaStack_Core_Data_MdbContext_array2List_2 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Data.MdbContext.array2List.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call Commit method without transaction.
        /// </summary>
        internal static string S031_MetaStack_Core_Data_MdbContext_Commit_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Data.MdbContext.Commit.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type derived from {0} was not found in service collection.
        /// </summary>
        internal static string S031_MetaStack_Core_Data_ObjectFactories_GetFactories_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Data.ObjectFactories.GetFactories.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the data array must be equal to the length of the array of field names.
        /// </summary>
        internal static string S031_MetaStack_Core_Data_writeData_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.Data.writeData.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object &apos;{0}&apos; with specified id  &apos;{1}&apos; not found in the database.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXProvider_ObjectNotFound {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXProvider.ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found the schema of the object &apos;{0}&apos;.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchema_ctor_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchema.ctor.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required element &apos;{0}&apos;.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchema_ParseXml_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchema.ParseXml.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attribute is required in the schema.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For an object type attribute, you must specify a schema.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_2 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FieldName &apos;{0}&apos; specified in the {1} is not in the attribute list.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_3 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; has an invalid data type.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_4 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A primary key is required for a table &apos;{0}&apos; that includes columns of type &apos;object&apos;.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_5 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied for user {0} to execute &apos;{1}&apos; of object &apos;{2}&apos;.
        /// </summary>
        internal static string S031_MetaStack_Core_SecurityAuthorizationExceptions_GetMessage_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.SecurityAuthorizationExceptions.GetMessage.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object schema &apos;{0}&apos; not found in database.
        /// </summary>
        internal static string S031_MetaStack_Core_SysCat_SysCatManager_getSchema_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.SysCat.SysCatManager.getSchema.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object schema &apos;{0}&apos; with the SyncState={1} not found in database.
        /// </summary>
        internal static string S031_MetaStack_Core_SysCat_SysCatManager_getSchema_2 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.SysCat.SysCatManager.getSchema.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum message length can not be less than 32 bytes.
        /// </summary>
        internal static string S031_MetaStack_Services_TCPServerService_Accept_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Services.TCPServerService.Accept.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SysCatConnection.
        /// </summary>
        internal static string SysCatConnection {
            get {
                return ResourceManager.GetString("SysCatConnection", resourceCulture);
            }
        }
    }
}
