//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S031.MetaStack.Json.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S031.MetaStack.Json.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON array must end with &apos;]&apos;..
        /// </summary>
        internal static string ArgumentException_ArrayMustEndWithBracket {
            get {
                return ResourceManager.GetString("ArgumentException_ArrayMustEndWithBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos;, got &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentException_ExpectedXButGotY {
            get {
                return ResourceManager.GetString("ArgumentException_ExpectedXButGotY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos;, differed at {1}..
        /// </summary>
        internal static string ArgumentException_ExpectedXDiferedAtY {
            get {
                return ResourceManager.GetString("ArgumentException_ExpectedXDiferedAtY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra characters in JSON input..
        /// </summary>
        internal static string ArgumentException_ExtraCharacters {
            get {
                return ResourceManager.GetString("ArgumentException_ExtraCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON numeric literal; extra dot..
        /// </summary>
        internal static string ArgumentException_ExtraDot {
            get {
                return ResourceManager.GetString("ArgumentException_ExtraDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete unicode character escape literal..
        /// </summary>
        internal static string ArgumentException_IncompleteEscapeLiteral {
            get {
                return ResourceManager.GetString("ArgumentException_IncompleteEscapeLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON string literal; incomplete escape sequence..
        /// </summary>
        internal static string ArgumentException_IncompleteEscapeSequence {
            get {
                return ResourceManager.GetString("ArgumentException_IncompleteEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON numeric literal; incomplete exponent..
        /// </summary>
        internal static string ArgumentException_IncompleteExponent {
            get {
                return ResourceManager.GetString("ArgumentException_IncompleteExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete JSON input..
        /// </summary>
        internal static string ArgumentException_IncompleteInput {
            get {
                return ResourceManager.GetString("ArgumentException_IncompleteInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON string literal format..
        /// </summary>
        internal static string ArgumentException_InvalidLiteralFormat {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidLiteralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leading zeros are not allowed..
        /// </summary>
        internal static string ArgumentException_LeadingZeros {
            get {
                return ResourceManager.GetString("ArgumentException_LeadingZeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} At line {1}, column {2}..
        /// </summary>
        internal static string ArgumentException_MessageAt {
            get {
                return ResourceManager.GetString("ArgumentException_MessageAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON numeric literal; no digit found..
        /// </summary>
        internal static string ArgumentException_NoDigitFound {
            get {
                return ResourceManager.GetString("ArgumentException_NoDigitFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON string is not closed..
        /// </summary>
        internal static string ArgumentException_StringNotClosed {
            get {
                return ResourceManager.GetString("ArgumentException_StringNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character &apos;{0}&apos;..
        /// </summary>
        internal static string ArgumentException_UnexpectedCharacter {
            get {
                return ResourceManager.GetString("ArgumentException_UnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON string literal; unexpected escape character..
        /// </summary>
        internal static string ArgumentException_UnexpectedEscapeCharacter {
            get {
                return ResourceManager.GetString("ArgumentException_UnexpectedEscapeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFormattedString from value type {0}..
        /// </summary>
        internal static string NotImplemented_GetFormattedString {
            get {
                return ResourceManager.GetString("NotImplemented_GetFormattedString", resourceCulture);
            }
        }
    }
}
