//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S031.MetaStack.Core.ORM.MsSql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S031.MetaStack.Core.ORM.MsSql.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attribute is required in the schema.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For an object type attribute, you must specify a schema.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_2 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FieldName &apos;{0}&apos; specified in the {1} is not in the attribute list.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_3 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; has an invalid data type.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_4 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A primary key is required for a table &apos;{0}&apos; that includes columns of type &apos;object&apos;.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_5 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property RefObjectName can&apos;t be empty.
        /// </summary>
        internal static string S031_MetaStack_Core_ORM_JMXSchemaProviderDB_normalize_6 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.ORM.JMXSchemaProviderDB.normalize.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object schema &apos;{0}&apos; not found in database.
        /// </summary>
        internal static string S031_MetaStack_Core_SysCat_SysCatManager_getSchema_1 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.SysCat.SysCatManager.getSchema.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object schema &apos;{0}&apos; with the SyncState={1} not found in database.
        /// </summary>
        internal static string S031_MetaStack_Core_SysCat_SysCatManager_getSchema_2 {
            get {
                return ResourceManager.GetString("S031.MetaStack.Core.SysCat.SysCatManager.getSchema.2", resourceCulture);
            }
        }
    }
}
